spring:
  application:
    name: orinote
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: profile, email
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orinote}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:orinote}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    openai:
      api-key: ${OPENAI_API_KEY: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}
      base-url: ${OPENAI_BASE_URL:https://openrouter.ai/api}
      chat:
        options:
          model: meta-llama/llama-4-maverick:free

server:
  forward-headers-strategy: framework

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'

jwt:
  secret: orinote-very-secret-key-should-be-long-and-random-2025

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}