spring:
  application:
    name: orinote
  mvc:
    problemdetails:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orinote}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:orinote}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    property-naming-strategy: SNAKE_CASE
  ai:
    openai:
      base-url: ${DOUBAO_URL}
      api-key: ${DOUBAO_API_KEY}
      chat:
        completions-path: ${DOUBAO_COMPLETIONS_PATH}
        options:
          model: ${DOUBAO_MODEL}

  #  vertex:
  #    ai:
  #      gemini:
  #        project-id: ${GEMINI_PROJECT_ID}
  #        location: ${GEMINI_LOCATION}
  #        chat:
  #          options:
  #            model: ${GEMINI_MODEL}

server:
  forward-headers-strategy: framework

logging:
  pattern:
    level: "trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %p"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: 'true'
