CREATE TABLE notes (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    note_type INT NOT NULL,
    head TEXT,
    body TEXT,
    tail TEXT,
    summary TEXT,
    is_deleted BOOLEAN DEFAULT FALSE,
    archived_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

--
--CREATE TABLE summaries (
--    id BIGSERIAL PRIMARY KEY,
--    title VARCHAR(255) NOT NULL,
--    content TEXT NOT NULL,
--    is_deleted BOOLEAN DEFAULT FALSE,
--    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
--    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
--    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
--);
--